changelog:
  exclude:
    labels:
      - kind/meta
  categories:
    - title: Breaking Changes
      labels:
        - kind/breaking-change
    - title: Enhancements
      labels:
        - kind/enhancement
    - title: Bug Fixes
      labels:
        - kind/bug
    - title: Dependencies
      labels:
        - area/dependencies
