name: Auto-Approve Safe PRs
on: pull_request
permissions: {}
jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - name: Save the PR number in an artifact
        shell: bash
        env:
          PR_NUM: ${{ github.event.number }}
        run: echo "$PR_NUM" > pr_num.txt
      - name: Upload the PR number
        uses: actions/upload-artifact@v4
        with:
          name: pr_num
          path: ./pr_num.txt
