name: CI

permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:
  merge_group:

concurrency:
  group: ci-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Lint and Formatting
            test: test:ci:lint
          - name: Typecheck and Data Validation
            test: test:ci:types
          - name: Unit Tests
            test: test:ci:unit
          - name: Build Validation
            test: test:ci:build

    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup

      - name: Run ${{ matrix.name }}
        run: npm run ${{ matrix.test }}

      - name: Validate manifest.json of the extension
        if: ${{ matrix.test == 'test:ci:build' }}
        uses: cardinalby/schema-validator-action@2166123eb256fa40baef7e22ab1379708425efc7 # v3.1.1
        with:
          file: ext/manifest.json
          schema: ./dev/data/chrome-manifest-schema.json
          fixSchemas: true
