name: Touch google token
on:
  schedule:
    - cron: "0 3 2 * *" # At 03:00 on day-of-month 2
  workflow_dispatch:
permissions: {}
jobs:
  fetchToken:
    runs-on: ubuntu-latest
    environment: cd
    steps:
      - uses: cardinalby/google-api-fetch-token-action@f455422472a558d48d939e77a65cdcec38e707b5 # pin@v1.0.4
        with:
          clientId: ${{ secrets.G_CLIENT_ID }}
          clientSecret: ${{ secrets.G_CLIENT_SECRET }}
          refreshToken: ${{ secrets.G_REFRESH_TOKEN }}
